FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../shared-libs /app/shared-libs
RUN pip install -e /app/shared-libs

COPY app /app/app

EXPOSE 8032

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8032"]
